import {
    APIError,
    APIErrorCode,
    AuthenticationError,
    BadInputError,
    ConflictError,
    DuplicateError,
    ErrorOptions,
    ForbiddenError,
    InternalServerError,
    NotFoundError,
    RateLimitError,
    ServerUnavailableError,
    UnknownError
} from './errors.js';

interface Response {
    readonly ok: boolean;
    readonly status: number;
    json(): Promise<any>;
}

/**
 * Parse an API Response into an APIError of the appropriate class.
 *
 * @param resp the server Response containing a potential APIError
 * @returns the APIError (as an instance of the appropriate sub-class) represented in the Response if it exists, otherwise undefined
 * @throws an Error if the Response was successful (ok = true)
 */
export async function parseError(resp: Response): Promise<APIError> {
    if (resp.ok) throw new Error('Error parsing is not supported for a successful Response (ok = true)');

    const body = (await resp.json().catch(() => {
        // The error response did not contain any JSON content
        return undefined;
    })) as ErrorOptions;

    // Validate whether or not the body matches the spec of an error code generated by this library
    const validBody = typeof body === 'object' && body !== null && !Array.isArray(body);
    const errorData = validBody ? body : {};

    const params = { status: resp.status, ...errorData };
    switch (resp.status) {
        case 400:
        case 422:
            return new BadInputError(params);
        case 401:
            return new AuthenticationError(params);
        case 403:
            return new ForbiddenError(params);
        case 404:
            return new NotFoundError(params);
        case 409: {
            if (params.errorCode === APIErrorCode.Duplicate) return new DuplicateError(params);
            return new ConflictError(params);
        }
        case 429:
            return new RateLimitError(params);
        case 500:
            return new InternalServerError(params);
        case 502:
            return new ServerUnavailableError(params);
        default:
            return new UnknownError(params);
    }
}
